services:
  popspace:
    image: popspace
    build: .
    container_name: popspace
    hostname: popspace
    environment:
      - REACT_APP_LIVEKIT_ENDPOINT=http://localhost:7880
      - LIVEKIT_API_KEY=APIZyzr2sN3d5Zq
      - LIVEKIT_SECRET_KEY=esHWyiSvfy7gye0gU2eCueSoeZW14Cz4VtsnflFNlM5e
      - DATABASE_URL=file:/data/db.sqlite?connection_limit=1
      - UNICORN_DATABASE_URL=/data/unicorn.sqlite
      - USER_FILES_DIRECTORY=/data/user-files
      - WALLPAPERS_DIRECTORY=/data/wallpapers
      - PUBLIC_URL=http://127.0.0.1:8888
      - APP_PORT=8888
    #env_file:
    #  - .env
    ports:
      - "8888:8888"  # UI server
      - "8889:8889"  # API server
      - "8890:8890"  # Socket server
      - "8891:8891"  # Collaborative document server
    volumes:
      - popspace_data:/data
  livekit:
    image: livekit/livekit-server:v0.15.6
    container_name: livekit
    hostname: livekit
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - ./livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml --node-ip 127.0.0.1

volumes:
  popspace_data: