services:
  popspace:
    image: xnohat/popspace:latest
    #build: .
    container_name: popspace
    hostname: popspace
    environment:
      - REACT_APP_LIVEKIT_ENDPOINT=https://livekit.360of.me
      - LIVEKIT_API_KEY=xxxxx
      - LIVEKIT_SECRET_KEY=xxxxxxxxxx
      - DATABASE_URL=file:/data/db.sqlite?connection_limit=1
      - UNICORN_DATABASE_URL=/data/unicorn.sqlite
      - USER_FILES_DIRECTORY=/data/user-files
      - WALLPAPERS_DIRECTORY=/data/wallpapers
      - PUBLIC_URL=https://work.360of.me
      - REACT_APP_HOST=work.360of.me
      - REACT_APP_PORT=443 #8888
      - REACT_APP_HERMES_HOST=work-hermes.360of.me
      - REACT_APP_HERMES_PORT=443 #8890
      - REACT_APP_API_HOST=work-api.360of.me
      - REACT_APP_API_PORT=443 #8889
      - REACT_APP_UNICORN_HOST=work-unicorn.360of.me
      - REACT_APP_UNICORN_PORT=443 #8891
      - REACT_APP_AUTH_USER=admin
      - REACT_APP_AUTH_PASSWORD=admin
    #env_file:
    #  - .env
    ports:
      - "8888:8888"  # UI server
      - "8889:8889"  # API server
      - "8890:8890"  # Socket server
      - "8891:8891"  # Collaborative document server
    volumes:
      - popspace_data:/data

volumes:
  popspace_data:
